export const ModalAction = {
  SHOW_MODAL: 'SHOW_MODAL',
};

export const UserAction = {
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_BY_GOOGLE: 'LOGIN_BY_GOOGLE',
  LOGIN_BY_GOOGLE_SUCCESS: 'LOGIN_BY_GOOGLE_SUCCESS',
  GET_INFO: 'GET_INFO',
  GET_INFO_SUCCESS: 'GET_INFO_SUCCESS',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT',
  GET_EARNINGS: 'GET_EARNINGS',
};

export const FeedbackAction = {
  CREATE_FEEDBACK: 'CREATE_FEEDBACK',
};

export const QuestionAction = {
  GET_STATE: 'GET_STATE',
  GET_STATE_SUCCESS: 'GET_STATE_SUCCESS',
  UPDATE_STATE: 'UPDATE_STATE',
  CLAIM: 'CLAIM',
  SKIP: 'SKIP',
  END_SESSION: 'END_SESSION',
  SEND_MESSAGE: 'SEND_MESSAGE',
  NEW_MESSAGE: 'NEW_MESSAGE',
};
