export const ModalAction = {
  SHOW_MODAL: 'SHOW_MODAL',
};

export const UserAction = {
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_BY_GOOGLE: 'LOGIN_BY_GOOGLE',
  LOGIN_BY_GOOGLE_SUCCESS: 'LOGIN_BY_GOOGLE_SUCCESS',
  GET_INFO: 'GET_INFO',
  GET_INFO_SUCCESS: 'GET_INFO_SUCCESS',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT',
};

export const FeedbackAction = {
  CREATE_FEEDBACK: 'CREATE_FEEDBACK',
};

export const QuestionAction = {
  GET_STATE: 'GET_STATE',
  GET_STATE_SUCCESS: 'GET_STATE_SUCCESS',
};
