export const ModalAction = {
  SHOW_MODAL: 'SHOW_MODAL',
};

export const UserAction = {
  LOGOUT: 'LOGOUT',
  LOGIN_WITH_GOOGLE: 'LOGIN_WITH_GOOGLE',
  LOGIN_WITH_GOOGLE_SUCCESS: 'LOGIN_WITH_GOOGLE_SUCCESS',
  GET_USERS: 'GET_USERS',
  DELETE_USER: 'DELETE_USER',
  UNDO_DELETE_USER: 'UNDO_DELETE_USER',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
};

export const ExpertAction = {
  GET_EXPERTS: 'GET_EXPERTS',
  CREATE_EXPERT: 'CREATE_EXPERT',
  UPDATE_EXPERT: 'UPDATE_EXPERT',
  DELETE_EXPERT: 'DELETE_EXPERT',
  UNDO_DELETE_EXPERT: 'UNDO_DELETE_EXPERT',
  GET_ACTIVE_EXPERTS: 'GET_ACTIVE_EXPERTS',
  GET_QUESTIONS: 'GET_QUESTIONS',
};

export const FeedbackAction = {
  GET_FEEDBACK: 'GET_FEEDBACK',
};

export const SubscriptionPackageAction = {
  GET_SUBSCRIPTION_PACKAGES: 'GET_SUBSCRIPTION_PACKAGES',
  UPDATE_SUBSCRIPTION_PACKAGE: 'UPDATE_SUBSCRIPTION_PACKAGE',
};

export const TransactionAction = {
  GET_TRANSACTIONS: 'GET_TRANSACTIONS',
};

export const QuestionAction = {
  GET_ACTIVE_QUESTIONS: 'GET_ACTIVE_QUESTIONS',
  GET_QUESTIONS: 'GET_QUESTIONS',
};


export const StatisticAction = {
  GET_STATISTICS: 'GET_STATISTICS',
};
