export const ModalKey = {
  ADD_EXPERT: 'ADD_EXPERT',
  CONFIRM_DELETE: 'CONFIRM_DELETE',
  UPDATE_EXPERT: 'UPDATE_EXPERT',
  CONFIRM_UNDO_DELETE: 'CONFIRM_UNDO_DELETE',
  UPDATE_USER: 'UPDATE_USER',
  ADD_USER: 'ADD_USER',
  UPDATE_SUBSCRIPTION_PACKAGE: 'UPDATE_SUBSCRIPTION_PACKAGE',
};
