export const ModalAction = {
  SHOW_MODAL: 'SHOW_MODAL',
};

export const UserAction = {
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_BY_GOOGLE: 'LOGIN_BY_GOOGLE',
  LOGIN_BY_GOOGLE_SUCCESS: 'LOGIN_BY_GOOGLE_SUCCESS',
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_BY_GOOGLE: 'SIGN_UP_BY_GOOGLE',
  SIGN_UP_BY_GOOGLE_SUCCESS: 'SIGN_UP_BY_GOOGLE_SUCCESS',
  GET_INFO: 'GET_INFO',
  GET_INFO_SUCCESS: 'GET_INFO_SUCCESS',
};
