export const ModalAction = {
  SHOW_MODAL: 'SHOW_MODAL',
};

export const UserAction = {
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_BY_GOOGLE: 'LOGIN_BY_GOOGLE',
  LOGIN_BY_GOOGLE_SUCCESS: 'LOGIN_BY_GOOGLE_SUCCESS',
  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_BY_GOOGLE: 'SIGNUP_BY_GOOGLE',
  SIGNUP_BY_GOOGLE_SUCCESS: 'SIGNUP_BY_GOOGLE_SUCCESS',
  GET_INFO: 'GET_INFO',
  GET_INFO_SUCCESS: 'GET_INFO_SUCCESS',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
};

export const FeedbackAction = {
  CREATE_FEEDBACK: 'CREATE_FEEDBACK',
};
