export const ModalAction = {
  SHOW_MODAL: 'SHOW_MODAL',
};

export const UserAction = {
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_BY_GOOGLE: 'LOGIN_BY_GOOGLE',
  LOGIN_BY_GOOGLE_SUCCESS: 'LOGIN_BY_GOOGLE_SUCCESS',
  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_BY_GOOGLE: 'SIGNUP_BY_GOOGLE',
  SIGNUP_BY_GOOGLE_SUCCESS: 'SIGNUP_BY_GOOGLE_SUCCESS',
  GET_INFO: 'GET_INFO',
  GET_INFO_SUCCESS: 'GET_INFO_SUCCESS',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  GET_BRAINTREE_CLIENT_TOKEN: 'GET_BRAINTREE_CLIENT_TOKEN',
  PURCHASE_CREDIT_PACKAGES: 'PURCHASE_CREDIT_PACKAGES',
};

export const FeedbackAction = {
  CREATE_FEEDBACK: 'CREATE_FEEDBACK',
};

export const SubscriptionAction = {
  GET_SUBSCRIPTION: 'GET_SUBSCRIPTION',
  GET_SUBSCRIPTION_SUCCESS: 'GET_SUBSCRIPTION_SUCCESS',
};

export const UserSubscriptionAction = {
  GET_USER_SUBSCRIPTION: 'GET_USER_SUBSCRIPTION',
  GET_USER_SUBSCRIPTION_SUCCESS: 'GET_USER_SUBSCRIPTION_SUCCESS',
};
