export const ModalKey = {
  FEEDBACK: 'FEEDBACK',
  PAYMENT: 'PAYMENT',
  MATCHING_EXPERT: 'MATCHING_EXPERT',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  QUESTION_DEAD: 'QUESTION_DEAD',
  RATE: 'RATE',
  ACTIVE_QUESTION: 'ACTIVE_QUESTION',
};
